portals: &portals

  above:
    org: ABoVE
    title: Search
    params:
      project:
        - ABoVE
    scripts:
      - edsc-portal.ornl.min.js

  airmoss:
    org: ORNL DAAC
    title: AirMOSS
    params:
      project:
        - AirMOSS
    logos:
      - id: ornl-daac-logo
        image: /images/portals/ornl/ornl-daac-logo-mono.png
        link: https://airmoss.ornl.gov
        title: ORNL DAAC AirMOSS Home
    scripts:
      - edsc-portal.ornl.min.js

  carve:
    org: ORNL DAAC
    title: CARVE
    params:
      project:
        - CARVE
    logos:
      - id: ornl-daac-logo
        image: /images/portals/ornl/ornl-daac-logo-mono.png
        link: https://carve.ornl.gov/
        title: ORNL DAAC CARVE Home
    scripts:
      - edsc-portal.ornl.min.js

  cwic:
    org: CWIC
    title: Search
    params:
      tag-key:
        - edsc.portal.cwic.collections
    logos:
      - id: ceos-logo
        image: /images/portals/cwic/ceos-logo.png
        link: http://ceos.org/
        title: CEOS Home
    scripts:
      - edsc-portal.cwic.js

  ornldaac:
    org: ORNL DAAC
    title: Search
    params:
      data_center:
        - ORNL_DAAC
    logos:
      - id: ornl-daac-logo
        image: /images/portals/ornl/ornl-daac-logo-mono.png
        link: https://daac.ornl.gov
        title: ORNL DAAC Home
    scripts:
      - edsc-portal.ornl.min.js

  podaac:
    org: PO.DAAC
    title: Search
    params:
      data_center:
        - PO.DAAC
    logos:
      - id: podaac-logo
        image: /images/portals/podaac/podaac_logo-mono.png
        link: https://podaac.jpl.nasa.gov
        title: PO.DAAC Home
    scripts:
      - edsc-portal.podaac.js

examples: &examples
  example:

  simple:
    params:
      echo_collection_id:
        - C203234523-LAADS

  complex:
    title: Complex
    params:
      echo_collection_id:
        - C203234523-LAADS
    logos:
      - image: http://placehold.it/75x50
        link: https://example.com/logo
    nav:
      - title: Example Link
        link: https://example.com/1
      - title: Another Example
        link: https://example.com/1
    scripts:
      - edsc-portal.example.min.js

defaults:
  <<: *examples
  <<: *portals

production:
  <<: *portals   
